In [12]:
import csv
import collections

term_list = ['sub', 'add', 'push', 'pop', 'call', 'cmp', 'lea']

initial_dict = {'sub': 0, 'add': 0, 'push': 0, 'pop': 0, 'call': 0, 'cmp': 0, 'lea': 0}

od = collections.OrderedDict(sorted(initial_dict.items()))

#print(od)

list_of_dict = [od.copy()]



In [13]:
filename = "/home/airobot/Desktop/bbs_csv/my_train_openssl_gcc.csv"

with open(filename, 'rb') as f:
    reader = csv.reader(f)
    i = 0
    
    for row in reader:
        cell = row[0]
        for line in cell.splitlines():
            #print(line)
            pos2 = line.find('*')
            #print(pos2)
            if pos2 > -1:
                if line[0:pos2] in list_of_dict[i]:
                    list_of_dict[i][line[0:pos2]] = list_of_dict[i][line[0:pos2]]+1
            else:
                if line[:] in list_of_dict[i]:
                    list_of_dict[i][line[:]] = list_of_dict[i][line[:]]+1
    
        #print(list_of_dict[i])
        i = i+1
        list_of_dict.append(od.copy())



In [14]:
from numpy import *
m = mat(zeros((7,7))) 

for index in range(len(term_list)):
    list_of_dict.sort(key=lambda obj:obj.get(term_list[index]), reverse=True)
    m[0,index] = list_of_dict[0]['add']
    m[1,index] = list_of_dict[1]['call']
    m[2,index] = list_of_dict[2]['cmp']
    m[3,index] = list_of_dict[3]['lea']
    m[4,index] = list_of_dict[4]['pop']
    m[5,index] = list_of_dict[5]['push']
    m[6,index] = list_of_dict[6]['sub']

print(m)



[[ 158.  390.   12.    2.    0.    0.  342.]
 [   0.    0.    1.   17.   96.    0.    0.]
 [   0.    0.    1.    0.    0.    5.    0.]
 [  31.    0.    1.   30.    0.    0.   64.]
 [   5.    0.    0.    6.    1.    0.    0.]
 [   0.    0.   19.    0.    0.    0.    0.]
 [  16.    1.    1.    0.    0.    0.    2.]]


In [26]:
'''
list_of_dict.sort(key=lambda obj:obj.get('add'), reverse=True)

for element in list_of_dict:
    print(element)
    
m[0,0] = list_of_dict[0]['add']
m[1,0] = list_of_dict[1]['call']
m[2,0] = list_of_dict[2]['cmp']
m[3,0] = list_of_dict[3]['lea']
m[4,0] = list_of_dict[4]['pop']
m[5,0] = list_of_dict[5]['push']
m[6,0] = list_of_dict[6]['sub']

list_of_dict.sort(key=lambda obj:obj.get('call'), reverse=True)

m[0,1] = list_of_dict[0]['add']
m[1,1] = list_of_dict[1]['call']
m[2,1] = list_of_dict[2]['cmp']
m[3,1] = list_of_dict[3]['lea']
m[4,1] = list_of_dict[4]['pop']
m[5,1] = list_of_dict[5]['push']
m[6,1] = list_of_dict[6]['sub']

list_of_dict.sort(key=lambda obj:obj.get('cmp'), reverse=True)

list_of_dict.sort(key=lambda obj:obj.get('lea'), reverse=True)

list_of_dict.sort(key=lambda obj:obj.get('pop'), reverse=True)

list_of_dict.sort(key=lambda obj:obj.get('push'), reverse=True)

list_of_dict.sort(key=lambda obj:obj.get('sub'), reverse=True)

'''

from scipy import spatial

import numpy as np

a = np.squeeze(np.asarray(m.reshape(1,49)))

kill = np.array([0,3,0,1,0,1,0,1,0,0,0,23,46,3,1,0,0,0,1,1,0,1,0,0,0,1,3,2,0,0,0,3,2,0,0,
 6,0,2,0,3,0,0,1,0,1,0,0,0,0])

print(b)

c_kill = 1 - spatial.distance.cosine(a, kill)

print(c_kill)

[ 0  3  0  1  0  1  0  1  0  0  0 23 46  3  1  0  0  0  1  1  0  1  0  0  0
  1  3  2  0  0  0  3  2  0  0  6  0  2  0  3  0  0  1  0  1  0  0  0  0]
0.123923492457


In [28]:
ln = np.array([0,3,2,1,0,0,3,2,0,2,1,5,4,1,1,1,1,0,2,2,0  
   ,3,0,0,0,0,0,3,0,0,0,6,0,0,0  
   ,6,0,6,0,0,0,0,1,0,1,0,0,1,0 ])

tar = np.array([2, 7, 1, 1, 0, 2, 1 ,1, 1, 0, 2,14, 0, 4  
 ,1, 1, 0, 0, 0, 3, 0 ,6, 3, 3, 0, 3, 5, 6  
 ,0, 0, 0, 6, 0, 0, 0 ,0, 0, 6, 0, 0, 0, 1  
 ,4, 3, 2, 0, 1, 0, 7 ])

c_ln = 1 - spatial.distance.cosine(a, ln)

print(c_ln)

0.390696569424


In [29]:
c_tar = 1 - spatial.distance.cosine(a, tar)

print(c_tar)

0.422975073163
